remove epub
Was failing on ReadTheDocs with the following error:
writing output... [ 88%] prompting-case-studies
writing output... [ 92%] prompting-custom-gpt
WARNING: unknown node type: <SubfigureGridHtml: <SubfigureGridItemHtml...><SubfigureGridItemHtml...><Sub ...>
WARNING: unknown node type: <SubfigureGridItemHtml: <image_node...>>

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/sphinx/cmd/build.py", line 337, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/sphinx/application.py", line 351, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 362, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 570, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 580, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/sphinx/builders/_epub_base.py", line 373, in write_doc
    super().write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 659, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/sphinx/writers/html.py", line 36, in translate
    self.document.walkabout(visitor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 1 more time]
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/docutils/nodes.py", line 199, in walkabout
    visitor.dispatch_departure(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/sphinx/util/docutils.py", line 588, in dispatch_departure
    super().dispatch_departure(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/docutils/nodes.py", line 2005, in dispatch_departure
    return method(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/docutils/nodes.py", line 2027, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: SubfigureGridItemHtml

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/gurobi-optimization-gurobi-ai-modeling/envs/latest/lib/python3.10/site-packages/docutils/nodes.py", line 2027, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: SubfigureGridItemHtml
The full traceback has been saved in /tmp/sphinx-err-qkbjj5cx.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!